### ISSUE TITLE
Slack Callback URL

### ISSUE THREAD

**Issue by callmemarv** [TNG/virtual-office#145]
Hi there 🙋  
I'm trying to setup virtual office and I think it is a great concept so thank you for setting this up! 😊 I ran into some issues with the Slack authentication though. Maybe you can help clearing things up. 😅 

I followed the instructions in the README file. I setup the webhooks for Slack and Zoom. I use ngrok.io to pipe them to my local machine. I built and booted the project in production mode. The client works fine and displays the office I configured. I noticed that I cannot login via Slack anywhere though. Refering to the config documentation I thought this option might be disabled. It was not disabled. I searched for the corresponding piece of code and made sure Slack authentication was not disabled. When booting the project again it displayed the Slack login. I tried to login but I get an HTTP status of 404 saying the Slack webhook endpoint (`/api/slack/callback`) would not exist. I checked `/api-docs/` as well as the code and I cannot find it anywhere. Is there something I'm missing?

**Comment by greimela** [comment]
Hi @callmemarv,

thanks for trying out Virtual Office!
This seems to be a typo in the README, the correct callback endpoint would be `auth/slack/callback`.

**Comment by callmemarv** [comment]
Works like a charm now. Thank you very much! 😊
